# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "jakarta.*" # Don't offer updates for new Jakarta EE spec versions
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: "org.eclipse.microprofile:microprofile-parent" # The major version of microprofile-parent is tied to the Jakarta EE version
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
