## This allows Github actions to build this project
name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v5
        name: checkout

      - uses: actions/setup-java@v5
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}
          distribution: 'temurin'
          cache: 'maven'

      - name: build with maven
        run: mvn -B --no-transfer-progress verify javadoc:javadoc --file pom.xml -Pvalidate-formatting
